version: '3.8'

services:
  playwright-tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - CI=true
      - NODE_ENV=test
    volumes:
      - ./test-results:/app/test-results
      - ./playwright-report:/app/playwright-report
    networks:
      - test-network

networks:
  test-network:
    driver: bridge